# Generated by Django 5.1 on 2024-08-31 15:28

import bookings.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date_booked',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='status',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='project_number',
            field=models.CharField(default='000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='reason',
            field=models.TextField(default='000000'),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(default=bookings.models.get_default_start_time),
        ),
        migrations.AddField(
            model_name='booking',
            name='use_location',
            field=models.CharField(default='Rutherford House', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='item_name',
            field=models.CharField(choices=[('mouse', 'Mouse'), ('monitor', 'Monitor'), ('blk2go', 'BLK2GO'), ('p40_scanner', 'P40 Scanner'), ('ipad', 'iPad'), ('pc', 'PC'), ('hdmi_cable', 'HDMI Cable'), ('power_bank', 'Power Bank'), ('total_station', 'Total Station'), ('ipad_pro', 'iPad Pro'), ('keyboard', 'Keyboard'), ('mouse_pad', 'Mouse Pad')], default='pc', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_division',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
