# Generated by Django 5.1 on 2024-09-08 16:10

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_date_booked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(default=bookings.models.get_default_end_time),
        ),
        migrations.AlterField(
            model_name='booking',
            name='project_number',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reason',
            field=models.TextField(),
        ),
    ]
