# Generated by Django 3.2.25 on 2024-09-28 23:14

from django.db import migrations, models
import uuid


def generate_confirmation_numbers(apps, schema_editor):
    Message = apps.get_model('bookings', 'Message')
    for message in Message.objects.all():
        if not message.confirmation_number:
            message.confirmation_number = uuid.uuid4()
            message.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='message',
            name='confirmation_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='message',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(generate_confirmation_numbers),  # This will populate confirmation numbers
    ]
