# Generated by Django 3.2.25 on 2024-09-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_auto_20240929_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='confirmation_number',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
