# Generated by Django 3.2.25 on 2024-09-28 23:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_message_confirmation_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='confirmation_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
