# Generated by Django 3.2.25 on 2024-10-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_alter_message_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='item_name',
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='name',
            field=models.CharField(choices=[('mouse', 'Mouse'), ('monitor', 'Monitor'), ('blk2go', 'BLK2GO'), ('p40_scanner', 'P40 Scanner'), ('ipad', 'iPad'), ('pc', 'PC'), ('hdmi_cable', 'HDMI Cable'), ('power_bank', 'Power Bank'), ('total_station', 'Total Station'), ('ipad_pro', 'iPad Pro'), ('keyboard', 'Keyboard'), ('mouse_pad', 'Mouse Pad')], default='----------', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(default='available', max_length=50),
        ),
    ]
