# Generated by Django 3.2.25 on 2024-10-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_auto_20241001_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(default='General Inquiry', max_length=255),
        ),
    ]
