# Generated by Django 5.1.1 on 2025-06-22 13:52

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0014_alter_message_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="confirmation_number",
            field=models.CharField(
                default=bookings.models.generate_confirmation_number,
                editable=False,
                max_length=8,
                unique=True,
            ),
        ),
    ]
