# Generated by Django 5.1.1 on 2025-06-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0015_loginattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnknownLoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("failed_attempts", models.PositiveIntegerField(default=0)),
                ("lockout_until", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
